"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

Base settings module for this Django project.

It follows Django's “Quick-start development settings” (See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/)
and is not suitable for production.

For different environments (e.g. local, staging, tests, production),
create dedicated settings modules that import this one
and then extend/override specific values as needed. */

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from config.paths import PROJECT_DIR
from config.settings.schemas import config_registry as config

# Project base directory
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = PROJECT_DIR

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config.django.secret_key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config.django.debug

ALLOWED_HOSTS = []

# Application definition

LOCAL_APPS = []

THIRD_PARTY_APPS = []

INSTALLED_APPS = [
    # Django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    *THIRD_PARTY_APPS,
    *LOCAL_APPS,
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {}
for alias, db_config in config.database.items():
    DATABASES[alias] = {
        "ENGINE": db_config.django_engine,
        "NAME": db_config.name,
        "USER": db_config.user,
        "PASSWORD": db_config.password.get_secret_value(),
        "HOST": db_config.host,
        "PORT": db_config.port,
    }

# Database routers
# https://docs.djangoproject.com/en/5.2/topics/db/multi-db/#automatic-database-routing
DATABASE_ROUTERS = ["config.database_router.AppDatabaseRouter"]

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Logging
# https://docs.djangoproject.com/en/5.2/topics/logging/
# Centralized logging is configured via Loguru in config.logger
# setup_logging() is called in manage.py and wsgi.py at application startup

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
}
